// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  call_to_action: dynamic(() => import("./CallToAction")),
  contact: dynamic(() => import("./Contact")),
  features: dynamic(() => import("./Features")),
  hero: dynamic(() => import("./Hero")),
  testimonials: dynamic(() => import("./Testimonials")),
  text_with_image: dynamic(() => import("./TextWithImage")),
};
